services:
  - type: web
    name: flask-ml-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_secret_key_here
